// Auto-generated data from Excel
const REPORT_DATA = {
  "section1": {
    "controlLabels": [
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C7",
      "C8"
    ],
    "numStudents": 55,
    "maxPerControl": 5,
    "mins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "maxs": [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5
    ],
    "avgs": [
      1.95,
      3.65,
      3.65,
      3.29,
      3.82,
      3.82,
      2.73,
      1.82
    ],
    "avgsResponded": [
      3.96,
      4.37,
      4.37,
      4.41,
      4.57,
      4.38,
      3.33,
      2.22
    ],
    "respondedCounts": [
      27,
      46,
      46,
      41,
      46,
      48,
      45,
      45
    ],
    "approvalPcts": [
      47.3,
      78.2,
      78.2,
      74.5,
      81.8,
      85.5,
      74.5,
      30.9
    ],
    "cumulativeMins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "cumulativeMaxs": [
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40
    ],
    "cumulativeAvgs": [
      1.95,
      5.6,
      9.25,
      12.55,
      16.36,
      20.18,
      22.91,
      24.73
    ],
    "cumulativeNota7": [
      4.0,
      8.0,
      12.0,
      16.0,
      20.0,
      24.0,
      28.0,
      32.0
    ],
    "boxplot": [
      {
        "min": 0,
        "q1": 0.0,
        "median": 0,
        "q3": 4.0,
        "max": 5,
        "mean": 1.95
      },
      {
        "min": 0,
        "q1": 3.0,
        "median": 5,
        "q3": 5.0,
        "max": 5,
        "mean": 3.65
      },
      {
        "min": 0,
        "q1": 3.0,
        "median": 5,
        "q3": 5.0,
        "max": 5,
        "mean": 3.65
      },
      {
        "min": 0,
        "q1": 1.5,
        "median": 4,
        "q3": 5.0,
        "max": 5,
        "mean": 3.29
      },
      {
        "min": 0,
        "q1": 4.0,
        "median": 5,
        "q3": 5.0,
        "max": 5,
        "mean": 3.82
      },
      {
        "min": 0,
        "q1": 4.0,
        "median": 4,
        "q3": 5.0,
        "max": 5,
        "mean": 3.82
      },
      {
        "min": 0,
        "q1": 2.5,
        "median": 3,
        "q3": 4.0,
        "max": 5,
        "mean": 2.73
      },
      {
        "min": 0,
        "q1": 1.0,
        "median": 2,
        "q3": 3.0,
        "max": 5,
        "mean": 1.82
      }
    ],
    "distributions": [
      [
        28,
        0,
        1,
        7,
        11,
        8
      ],
      [
        9,
        0,
        3,
        6,
        8,
        29
      ],
      [
        9,
        0,
        3,
        6,
        8,
        29
      ],
      [
        14,
        0,
        0,
        5,
        14,
        22
      ],
      [
        9,
        0,
        1,
        1,
        15,
        29
      ],
      [
        7,
        0,
        1,
        5,
        17,
        25
      ],
      [
        10,
        0,
        4,
        23,
        17,
        1
      ],
      [
        10,
        16,
        12,
        10,
        5,
        2
      ]
    ],
    "heatmap": {
      "names": [
        "ÁLAMOS NILO, SEBASTIÁN ALONSO",
        "ALARCON RETAMAL, MATHIAS FRANCOIS",
        "ALVEAL ESPINOZA, VICENTE BALTAZAR",
        "BARROS BARCELÓ, LUIS",
        "BEAUJANOT SILVA, ELISA MARÍA",
        "BUSTOS DE LA FUENTE, IGNACIO",
        "CAÑAS ETCHEGARAY, PEDRO JOSÉ",
        "CARRASCO VALENZUELA, NICOLÁS AGUSTÍN",
        "CASANOVA NORSA, JOSÉ PABLO",
        "CASTAGNOLI CÁCERES, MATIAS ALEJANDRO",
        "CHAURIYE AGUAD, LUCAS ANDRÉS",
        "COMPARINI JIMÉNEZ, LUCA GUILLERMO",
        "CONTRERAS CHÁVEZ, VICENTE IGNACIO",
        "CORREA GILLET, TOMÁS",
        "COVARRUBIAS MARINKOVIC, SEBASTIÁN",
        "DUARTE LÓPEZ, OLIVER MARCELO",
        "FERNÁNDEZ CRUZ, MARÍA ISABEL",
        "FRIAS ISARN, MARÍA JOSÉ",
        "GONZÁLEZ WERTH, CANDELARIA",
        "HERRERA DEL REAL, BARTOLOMÉ JOSÉ",
        "IBÁÑEZ WRAGG, FELIPE ALBERTO",
        "JIMÉNEZ VIDAL, RODRIGO SEBASTIÁN",
        "LANGLOIS BUCHHOLTZ, BENJAMIN JOSE",
        "LANGLOIS PALMA, CRISTOBAL",
        "LAVÍN VIAL, JOSE LUIS",
        "LÓPEZ LERNER, DANIEL ALEJANDRO",
        "MARTIJA JOANNON, FLORENCIA",
        "MARTIN FLORES, BENJAMÍN IGNACIO",
        "MATAS SIRI, JAIME IGNACIO",
        "MELLA MATAS, ANDRÉS IGNACIO",
        "MUÑOZ ARÉVALO, MARTÍN ALONSO",
        "MUÑOZ HERNÁNDEZ, LORENZO ANTONIO",
        "MUÑOZ MERINO, CRISTÓBAL",
        "NOGUEIRA LARENAS, MARÍA TERESA",
        "OLIVA BUCHER, TOMAS ANDRES",
        "ORELLANA FERRAN, AGUSTÍN",
        "PADILLA VERA, MATÍAS AGUSTÍN",
        "RAMÍREZ FERNÁNDEZ, JAVIERA PAZ",
        "RÍOS BARROS, GUSTAVO",
        "ROMÁN FORTEZA, MANUEL",
        "SANTIBÁÑEZ BALBOA, JAVIERA PAZ",
        "TAGLE ASPILLAGA, IGNACIO",
        "TRAVERSO IGLESIS, NICOLÁS",
        "TRIVELLI MERINO, MANUEL JOSÉ",
        "URETA INGLESI, AGUSTINA",
        "VALENZUELA MIRANDA, MARTÍN",
        "VALENZUELA RODRÍGUEZ, FRANCINETT ALEXANDER",
        "VASCONCELLO ORTIZ, ANGELO NICOLÁS",
        "VIAL LECAROS, EDUARDO ALBERTO",
        "VICENTE VALENZUELA, SANTIAGO JUAN",
        "VIEL DE LA MAZA, RAIMUNDO",
        "VILLARROEL MELLADO, CONSTANZA ANDREA",
        "WAHL GONZÁLEZ, MARÍA SOFÍA",
        "YACONI IRÍZAR, LUCAS",
        "ZAÑARTU FERNÁNDEZ, FEDERICO"
      ],
      "scores": [
        [
          0,
          5,
          5,
          4,
          0,
          4,
          3,
          1
        ],
        [
          4,
          0,
          0,
          0,
          5,
          5,
          3,
          3
        ],
        [
          5,
          0,
          0,
          5,
          0,
          5,
          4,
          0
        ],
        [
          3,
          2,
          2,
          5,
          5,
          4,
          3,
          4
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          3,
          1
        ],
        [
          5,
          5,
          5,
          4,
          4,
          5,
          4,
          4
        ],
        [
          0,
          4,
          4,
          5,
          4,
          4,
          3,
          2
        ],
        [
          0,
          4,
          4,
          0,
          5,
          4,
          0,
          0
        ],
        [
          4,
          4,
          4,
          4,
          5,
          3,
          4,
          5
        ],
        [
          4,
          3,
          3,
          5,
          5,
          3,
          3,
          3
        ],
        [
          0,
          5,
          5,
          3,
          0,
          0,
          4,
          0
        ],
        [
          0,
          0,
          0,
          5,
          5,
          5,
          3,
          1
        ],
        [
          3,
          5,
          5,
          0,
          4,
          5,
          0,
          4
        ],
        [
          3,
          3,
          3,
          0,
          5,
          4,
          3,
          2
        ],
        [
          3,
          5,
          5,
          0,
          5,
          0,
          4,
          0
        ],
        [
          0,
          5,
          5,
          3,
          5,
          4,
          5,
          2
        ],
        [
          3,
          3,
          3,
          3,
          0,
          2,
          3,
          2
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          2,
          2
        ],
        [
          0,
          4,
          4,
          5,
          4,
          4,
          4,
          1
        ],
        [
          4,
          5,
          5,
          4,
          4,
          5,
          4,
          3
        ],
        [
          5,
          5,
          5,
          4,
          5,
          4,
          2,
          3
        ],
        [
          0,
          5,
          5,
          0,
          5,
          0,
          0,
          3
        ],
        [
          0,
          3,
          3,
          5,
          0,
          4,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          4,
          3,
          4,
          1
        ],
        [
          3,
          5,
          5,
          0,
          5,
          5,
          3,
          1
        ],
        [
          2,
          4,
          4,
          5,
          5,
          4,
          4,
          1
        ],
        [
          0,
          5,
          5,
          5,
          5,
          5,
          3,
          2
        ],
        [
          0,
          5,
          5,
          4,
          0,
          0,
          0,
          0
        ],
        [
          0,
          5,
          5,
          4,
          4,
          4,
          4,
          1
        ],
        [
          0,
          5,
          5,
          5,
          4,
          5,
          4,
          0
        ],
        [
          5,
          5,
          5,
          5,
          5,
          5,
          3,
          0
        ],
        [
          0,
          5,
          5,
          5,
          5,
          5,
          2,
          1
        ],
        [
          4,
          3,
          3,
          4,
          3,
          0,
          3,
          3
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          4,
          1
        ],
        [
          0,
          5,
          5,
          3,
          5,
          4,
          0,
          1
        ],
        [
          0,
          0,
          0,
          4,
          4,
          0,
          3,
          1
        ],
        [
          5,
          5,
          5,
          4,
          4,
          4,
          3,
          5
        ],
        [
          0,
          5,
          5,
          0,
          2,
          5,
          0,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          4,
          0,
          0
        ],
        [
          0,
          0,
          0,
          5,
          4,
          5,
          3,
          3
        ],
        [
          0,
          3,
          3,
          0,
          4,
          4,
          3,
          1
        ],
        [
          0,
          5,
          5,
          0,
          0,
          5,
          4,
          1
        ],
        [
          4,
          2,
          2,
          5,
          5,
          5,
          3,
          3
        ],
        [
          0,
          5,
          5,
          0,
          5,
          5,
          0,
          4
        ],
        [
          4,
          5,
          5,
          5,
          5,
          5,
          3,
          3
        ],
        [
          4,
          5,
          5,
          4,
          4,
          3,
          3,
          1
        ],
        [
          4,
          5,
          5,
          5,
          5,
          5,
          3,
          2
        ],
        [
          0,
          0,
          0,
          4,
          5,
          3,
          2,
          2
        ],
        [
          3,
          2,
          2,
          4,
          5,
          4,
          4,
          2
        ],
        [
          4,
          5,
          5,
          5,
          5,
          4,
          4,
          3
        ],
        [
          5,
          5,
          5,
          4,
          4,
          5,
          4,
          2
        ],
        [
          5,
          5,
          5,
          5,
          4,
          5,
          4,
          4
        ],
        [
          5,
          5,
          5,
          5,
          5,
          5,
          3,
          1
        ],
        [
          4,
          5,
          5,
          3,
          5,
          5,
          3,
          2
        ]
      ],
      "totals": [
        22,
        20,
        19,
        28,
        27,
        36,
        26,
        17,
        33,
        29,
        17,
        19,
        26,
        23,
        22,
        29,
        19,
        27,
        26,
        34,
        33,
        18,
        15,
        12,
        27,
        29,
        30,
        14,
        27,
        28,
        33,
        28,
        23,
        28,
        23,
        12,
        35,
        19,
        0,
        4,
        20,
        18,
        20,
        29,
        24,
        35,
        29,
        34,
        16,
        26,
        35,
        34,
        37,
        34,
        32
      ]
    },
    "ranking": {
      "names": [
        "WAHL GONZÁLEZ, MARÍA SOFÍA",
        "BUSTOS DE LA FUENTE, IGNACIO",
        "PADILLA VERA, MATÍAS AGUSTÍN",
        "VALENZUELA MIRANDA, MARTÍN",
        "VIEL DE LA MAZA, RAIMUNDO",
        "HERRERA DEL REAL, BARTOLOMÉ JOSÉ",
        "VASCONCELLO ORTIZ, ANGELO NICOLÁS",
        "VILLARROEL MELLADO, CONSTANZA ANDREA",
        "YACONI IRÍZAR, LUCAS",
        "CASANOVA NORSA, JOSÉ PABLO",
        "IBÁÑEZ WRAGG, FELIPE ALBERTO",
        "MUÑOZ ARÉVALO, MARTÍN ALONSO",
        "ZAÑARTU FERNÁNDEZ, FEDERICO",
        "MARTIJA JOANNON, FLORENCIA",
        "CASTAGNOLI CÁCERES, MATIAS ALEJANDRO"
      ],
      "totals": [
        37,
        36,
        35,
        35,
        35,
        34,
        34,
        34,
        34,
        33,
        33,
        33,
        32,
        30,
        29
      ]
    }
  },
  "section2": {
    "controlLabels": [
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C7",
      "C8"
    ],
    "numStudents": 49,
    "maxPerControl": 5,
    "mins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "maxs": [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      4
    ],
    "avgs": [
      2.76,
      3.39,
      3.47,
      2.88,
      3.39,
      2.63,
      1.84,
      1.57
    ],
    "avgsResponded": [
      4.22,
      4.37,
      4.86,
      4.27,
      4.49,
      3.39,
      3.33,
      2.03
    ],
    "respondedCounts": [
      32,
      38,
      35,
      33,
      37,
      38,
      27,
      38
    ],
    "approvalPcts": [
      63.3,
      73.5,
      71.4,
      67.3,
      75.5,
      59.2,
      44.9,
      26.5
    ],
    "cumulativeMins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "cumulativeMaxs": [
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40
    ],
    "cumulativeAvgs": [
      2.76,
      6.14,
      9.61,
      12.49,
      15.88,
      18.51,
      20.35,
      21.92
    ],
    "cumulativeNota7": [
      4.0,
      8.0,
      12.0,
      16.0,
      20.0,
      24.0,
      28.0,
      32.0
    ],
    "boxplot": [
      {
        "min": 0,
        "q1": 0,
        "median": 4,
        "q3": 5,
        "max": 5,
        "mean": 2.76
      },
      {
        "min": 0,
        "q1": 2,
        "median": 4,
        "q3": 5,
        "max": 5,
        "mean": 3.39
      },
      {
        "min": 0,
        "q1": 0,
        "median": 5,
        "q3": 5,
        "max": 5,
        "mean": 3.47
      },
      {
        "min": 0,
        "q1": 0,
        "median": 4,
        "q3": 4,
        "max": 5,
        "mean": 2.88
      },
      {
        "min": 0,
        "q1": 3,
        "median": 4,
        "q3": 5,
        "max": 5,
        "mean": 3.39
      },
      {
        "min": 0,
        "q1": 2,
        "median": 3,
        "q3": 4,
        "max": 5,
        "mean": 2.63
      },
      {
        "min": 0,
        "q1": 0,
        "median": 2,
        "q3": 3,
        "max": 5,
        "mean": 1.84
      },
      {
        "min": 0,
        "q1": 1,
        "median": 2,
        "q3": 3,
        "max": 4,
        "mean": 1.57
      }
    ],
    "distributions": [
      [
        17,
        0,
        1,
        6,
        10,
        15
      ],
      [
        11,
        1,
        1,
        5,
        7,
        24
      ],
      [
        14,
        0,
        0,
        0,
        5,
        30
      ],
      [
        16,
        0,
        0,
        2,
        20,
        11
      ],
      [
        12,
        0,
        0,
        3,
        13,
        21
      ],
      [
        11,
        1,
        8,
        11,
        11,
        7
      ],
      [
        22,
        0,
        5,
        11,
        8,
        3
      ],
      [
        11,
        13,
        12,
        12,
        1,
        0
      ]
    ],
    "heatmap": {
      "names": [
        "ABBOTT BARZELATTO, MARTÍN ANDRÉS",
        "AGÜERO MONTECINO, JUAN PABLO",
        "ARAYA DERPICH, RODRIGO ANTONIO",
        "ARENAS ABURTO, PAZ ANDREA",
        "ARTEAGA CORREA, ISIDORA",
        "BALTRA ESCOBAR, CRISTÓBAL",
        "BARRA BURGOS, VALENTINA IGNACIA",
        "BECA CLARO, NICOLÁS",
        "CAMPOS SOTO, MARTÍN GUILLERMO SEBASTIÁN",
        "CANO ARAYA, BENJAMÍN ALONSO",
        "CERDA OYARZÚN, JUAN PABLO",
        "CHARPENTIER ALEGRÍA, RENATO TOMÁS",
        "CID YURAS, ALFONSO PATRICIO",
        "COURT RODRÍGUEZ, VICENTE",
        "FOXLEY BOLOCCO, MAXIMILIANO",
        "GALLARDO VÁSQUEZ, ESTEBAN ANDRÉS",
        "GALLO DE TRENQUALYE, JOSÉ MIGUEL",
        "GARCÍA DE LA HUERTA ROJAS, ALICIA",
        "KITA TAMASHIRO, SARA SIZUE",
        "KOLUBAKIN DE LA JARA, AGUSTINA",
        "LEHUEDÉ DÍAZ, TOMÁS",
        "LIBEDINSKY HAN, GABRIEL DOV",
        "MARTÍNEZ MARTÍNEZ, JOAQUÍN ALFONSO",
        "MARTÍNEZ MATUS, FERNANDO ANDRÉS",
        "MATTA CABRERA, JOSÉ",
        "NAVARRO ARAVENA, DANIEL IGNACIO",
        "PATIÑO SOLÍS, BÁRBARA",
        "PÉREZ ZAMORANO, FRANCISCA IGNACIA",
        "PHILIPPI YUNUSIC, NICOLÁS",
        "PUELMA VERGARA, ANTONIA ISIDORA",
        "REYES BECKER, TOMÁS FRANCISCO",
        "REYES COVARRUBIAS, BENJAMÍN ALONSO",
        "RIESCO VALDÉS, MARIA MERCEDES",
        "RIVADENEIRA BEZANILLA, LEÓN",
        "RIVAS VÁSQUEZ, JOAQUÍN RICARDO SEGUNDO",
        "ROJAS ARIAS, FRANCISCO ARTURO",
        "ROZAS VARGAS, JORGE",
        "SALAS GONZÁLEZ, VANESSA ALEJANDRA",
        "SANHUEZA PINO, IGNACIO ALONSO",
        "SAUMA GUZMÁN, TRINIDAD CONSTANZA",
        "SOBARZO VIDAL, DAVID ALEJANDRO",
        "SOTO MUENA, LUIS IGNACIO",
        "SOTO RODRÍGUEZ, VIVIANA FRANCISCA",
        "TASSARA MOLINA, VITTORIO VINCENZO",
        "VERGARA URETA, AGUSTÍN JESÚS",
        "VÍLCHEZ URIBE, VALERY DANIELA",
        "WEIFFENBACH VIVES, SOFÍA",
        "WITTIG ALTMANN, TOMÁS",
        "YÁÑEZ ANDRADE, MARTÍN SAMUEL"
      ],
      "scores": [
        [
          2,
          5,
          5,
          5,
          5,
          5,
          0,
          2
        ],
        [
          4,
          3,
          0,
          4,
          3,
          2,
          0,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          4,
          2,
          2,
          1
        ],
        [
          5,
          5,
          5,
          4,
          5,
          3,
          4,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          0
        ],
        [
          4,
          5,
          5,
          5,
          5,
          3,
          3,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3
        ],
        [
          4,
          4,
          5,
          4,
          5,
          5,
          0,
          3
        ],
        [
          5,
          4,
          5,
          4,
          4,
          4,
          4,
          2
        ],
        [
          5,
          5,
          5,
          5,
          4,
          5,
          3,
          3
        ],
        [
          0,
          5,
          4,
          4,
          0,
          2,
          4,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          2,
          0,
          1
        ],
        [
          0,
          3,
          5,
          0,
          5,
          5,
          0,
          3
        ],
        [
          4,
          2,
          5,
          4,
          5,
          3,
          3,
          1
        ],
        [
          5,
          5,
          5,
          5,
          4,
          3,
          3,
          0
        ],
        [
          5,
          0,
          0,
          4,
          0,
          0,
          0,
          3
        ],
        [
          3,
          5,
          4,
          5,
          5,
          4,
          0,
          2
        ],
        [
          4,
          4,
          5,
          3,
          4,
          2,
          3,
          1
        ],
        [
          0,
          5,
          5,
          5,
          4,
          4,
          3,
          4
        ],
        [
          0,
          3,
          5,
          0,
          5,
          5,
          3,
          1
        ],
        [
          0,
          4,
          5,
          0,
          4,
          0,
          3,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          5,
          4,
          2,
          2
        ],
        [
          5,
          4,
          5,
          4,
          5,
          5,
          4,
          2
        ],
        [
          5,
          5,
          5,
          4,
          4,
          4,
          4,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          0,
          4,
          3,
          0,
          0
        ],
        [
          5,
          3,
          4,
          4,
          5,
          1,
          2,
          1
        ],
        [
          4,
          5,
          4,
          5,
          5,
          4,
          5,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          5,
          3,
          2,
          3
        ],
        [
          0,
          3,
          5,
          4,
          4,
          3,
          4,
          1
        ],
        [
          4,
          5,
          5,
          4,
          5,
          4,
          4,
          3
        ],
        [
          4,
          5,
          5,
          4,
          4,
          3,
          2,
          3
        ],
        [
          4,
          5,
          0,
          4,
          4,
          4,
          4,
          1
        ],
        [
          0,
          1,
          5,
          3,
          3,
          0,
          0,
          1
        ],
        [
          3,
          5,
          0,
          0,
          3,
          0,
          0,
          0
        ],
        [
          3,
          4,
          5,
          4,
          5,
          2,
          3,
          1
        ],
        [
          3,
          5,
          5,
          0,
          5,
          4,
          5,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0
        ],
        [
          3,
          4,
          5,
          5,
          5,
          2,
          3,
          1
        ],
        [
          5,
          5,
          5,
          5,
          5,
          3,
          0,
          1
        ],
        [
          4,
          5,
          5,
          5,
          5,
          4,
          0,
          1
        ],
        [
          3,
          5,
          4,
          5,
          5,
          4,
          3,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          2
        ],
        [
          5,
          5,
          5,
          4,
          5,
          2,
          0,
          2
        ],
        [
          5,
          5,
          5,
          4,
          4,
          3,
          5,
          3
        ]
      ],
      "totals": [
        29,
        18,
        0,
        28,
        33,
        5,
        33,
        3,
        30,
        32,
        35,
        21,
        3,
        21,
        27,
        30,
        12,
        28,
        26,
        30,
        22,
        18,
        0,
        32,
        34,
        34,
        0,
        22,
        25,
        34,
        0,
        0,
        32,
        24,
        34,
        30,
        26,
        13,
        11,
        27,
        30,
        3,
        28,
        29,
        29,
        29,
        2,
        28,
        34
      ]
    },
    "ranking": {
      "names": [
        "CERDA OYARZÚN, JUAN PABLO",
        "MATTA CABRERA, JOSÉ",
        "NAVARRO ARAVENA, DANIEL IGNACIO",
        "PUELMA VERGARA, ANTONIA ISIDORA",
        "RIVAS VÁSQUEZ, JOAQUÍN RICARDO SEGUNDO",
        "YÁÑEZ ANDRADE, MARTÍN SAMUEL",
        "ARTEAGA CORREA, ISIDORA",
        "BARRA BURGOS, VALENTINA IGNACIA",
        "CANO ARAYA, BENJAMÍN ALONSO",
        "MARTÍNEZ MATUS, FERNANDO ANDRÉS",
        "RIESCO VALDÉS, MARIA MERCEDES",
        "CAMPOS SOTO, MARTÍN GUILLERMO SEBASTIÁN",
        "GALLARDO VÁSQUEZ, ESTEBAN ANDRÉS",
        "KOLUBAKIN DE LA JARA, AGUSTINA",
        "ROJAS ARIAS, FRANCISCO ARTURO"
      ],
      "totals": [
        35,
        34,
        34,
        34,
        34,
        34,
        33,
        33,
        32,
        32,
        32,
        30,
        30,
        30,
        30
      ]
    }
  },
  "combined": {
    "controlLabels": [
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C7",
      "C8"
    ],
    "numStudents": 104,
    "maxPerControl": 5,
    "mins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "maxs": [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5
    ],
    "avgs": [
      2.33,
      3.53,
      3.57,
      3.1,
      3.62,
      3.26,
      2.31,
      1.7
    ],
    "avgsResponded": [
      4.1,
      4.37,
      4.58,
      4.35,
      4.53,
      3.94,
      3.33,
      2.13
    ],
    "respondedCounts": [
      59,
      84,
      81,
      74,
      83,
      86,
      72,
      83
    ],
    "approvalPcts": [
      54.8,
      76.0,
      75.0,
      71.2,
      78.8,
      73.1,
      60.6,
      28.8
    ],
    "cumulativeMins": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "cumulativeMaxs": [
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40
    ],
    "cumulativeAvgs": [
      2.33,
      5.86,
      9.42,
      12.52,
      16.13,
      19.39,
      21.7,
      23.4
    ],
    "cumulativeNota7": [
      4.0,
      8.0,
      12.0,
      16.0,
      20.0,
      24.0,
      28.0,
      32.0
    ],
    "boxplot": [
      {
        "min": 0,
        "q1": 0.0,
        "median": 3.0,
        "q3": 4.0,
        "max": 5,
        "mean": 2.33
      },
      {
        "min": 0,
        "q1": 3.0,
        "median": 5.0,
        "q3": 5.0,
        "max": 5,
        "mean": 3.53
      },
      {
        "min": 0,
        "q1": 2.75,
        "median": 5.0,
        "q3": 5.0,
        "max": 5,
        "mean": 3.57
      },
      {
        "min": 0,
        "q1": 0.0,
        "median": 4.0,
        "q3": 5.0,
        "max": 5,
        "mean": 3.1
      },
      {
        "min": 0,
        "q1": 3.75,
        "median": 4.0,
        "q3": 5.0,
        "max": 5,
        "mean": 3.62
      },
      {
        "min": 0,
        "q1": 2.0,
        "median": 4.0,
        "q3": 5.0,
        "max": 5,
        "mean": 3.26
      },
      {
        "min": 0,
        "q1": 0.0,
        "median": 3.0,
        "q3": 4.0,
        "max": 5,
        "mean": 2.31
      },
      {
        "min": 0,
        "q1": 1.0,
        "median": 2.0,
        "q3": 3.0,
        "max": 5,
        "mean": 1.7
      }
    ],
    "distributions": [
      [
        45,
        0,
        2,
        13,
        21,
        23
      ],
      [
        20,
        1,
        4,
        11,
        15,
        53
      ],
      [
        23,
        0,
        3,
        6,
        13,
        59
      ],
      [
        30,
        0,
        0,
        7,
        34,
        33
      ],
      [
        21,
        0,
        1,
        4,
        28,
        50
      ],
      [
        18,
        1,
        9,
        16,
        28,
        32
      ],
      [
        32,
        0,
        9,
        34,
        25,
        4
      ],
      [
        21,
        29,
        24,
        22,
        6,
        2
      ]
    ],
    "heatmap": {
      "names": [
        "ÁLAMOS NILO, SEBASTIÁN ALONSO",
        "ALARCON RETAMAL, MATHIAS FRANCOIS",
        "ALVEAL ESPINOZA, VICENTE BALTAZAR",
        "BARROS BARCELÓ, LUIS",
        "BEAUJANOT SILVA, ELISA MARÍA",
        "BUSTOS DE LA FUENTE, IGNACIO",
        "CAÑAS ETCHEGARAY, PEDRO JOSÉ",
        "CARRASCO VALENZUELA, NICOLÁS AGUSTÍN",
        "CASANOVA NORSA, JOSÉ PABLO",
        "CASTAGNOLI CÁCERES, MATIAS ALEJANDRO",
        "CHAURIYE AGUAD, LUCAS ANDRÉS",
        "COMPARINI JIMÉNEZ, LUCA GUILLERMO",
        "CONTRERAS CHÁVEZ, VICENTE IGNACIO",
        "CORREA GILLET, TOMÁS",
        "COVARRUBIAS MARINKOVIC, SEBASTIÁN",
        "DUARTE LÓPEZ, OLIVER MARCELO",
        "FERNÁNDEZ CRUZ, MARÍA ISABEL",
        "FRIAS ISARN, MARÍA JOSÉ",
        "GONZÁLEZ WERTH, CANDELARIA",
        "HERRERA DEL REAL, BARTOLOMÉ JOSÉ",
        "IBÁÑEZ WRAGG, FELIPE ALBERTO",
        "JIMÉNEZ VIDAL, RODRIGO SEBASTIÁN",
        "LANGLOIS BUCHHOLTZ, BENJAMIN JOSE",
        "LANGLOIS PALMA, CRISTOBAL",
        "LAVÍN VIAL, JOSE LUIS",
        "LÓPEZ LERNER, DANIEL ALEJANDRO",
        "MARTIJA JOANNON, FLORENCIA",
        "MARTIN FLORES, BENJAMÍN IGNACIO",
        "MATAS SIRI, JAIME IGNACIO",
        "MELLA MATAS, ANDRÉS IGNACIO",
        "MUÑOZ ARÉVALO, MARTÍN ALONSO",
        "MUÑOZ HERNÁNDEZ, LORENZO ANTONIO",
        "MUÑOZ MERINO, CRISTÓBAL",
        "NOGUEIRA LARENAS, MARÍA TERESA",
        "OLIVA BUCHER, TOMAS ANDRES",
        "ORELLANA FERRAN, AGUSTÍN",
        "PADILLA VERA, MATÍAS AGUSTÍN",
        "RAMÍREZ FERNÁNDEZ, JAVIERA PAZ",
        "RÍOS BARROS, GUSTAVO",
        "ROMÁN FORTEZA, MANUEL",
        "SANTIBÁÑEZ BALBOA, JAVIERA PAZ",
        "TAGLE ASPILLAGA, IGNACIO",
        "TRAVERSO IGLESIS, NICOLÁS",
        "TRIVELLI MERINO, MANUEL JOSÉ",
        "URETA INGLESI, AGUSTINA",
        "VALENZUELA MIRANDA, MARTÍN",
        "VALENZUELA RODRÍGUEZ, FRANCINETT ALEXANDER",
        "VASCONCELLO ORTIZ, ANGELO NICOLÁS",
        "VIAL LECAROS, EDUARDO ALBERTO",
        "VICENTE VALENZUELA, SANTIAGO JUAN",
        "VIEL DE LA MAZA, RAIMUNDO",
        "VILLARROEL MELLADO, CONSTANZA ANDREA",
        "WAHL GONZÁLEZ, MARÍA SOFÍA",
        "YACONI IRÍZAR, LUCAS",
        "ZAÑARTU FERNÁNDEZ, FEDERICO",
        "ABBOTT BARZELATTO, MARTÍN ANDRÉS",
        "AGÜERO MONTECINO, JUAN PABLO",
        "ARAYA DERPICH, RODRIGO ANTONIO",
        "ARENAS ABURTO, PAZ ANDREA",
        "ARTEAGA CORREA, ISIDORA",
        "BALTRA ESCOBAR, CRISTÓBAL",
        "BARRA BURGOS, VALENTINA IGNACIA",
        "BECA CLARO, NICOLÁS",
        "CAMPOS SOTO, MARTÍN GUILLERMO SEBASTIÁN",
        "CANO ARAYA, BENJAMÍN ALONSO",
        "CERDA OYARZÚN, JUAN PABLO",
        "CHARPENTIER ALEGRÍA, RENATO TOMÁS",
        "CID YURAS, ALFONSO PATRICIO",
        "COURT RODRÍGUEZ, VICENTE",
        "FOXLEY BOLOCCO, MAXIMILIANO",
        "GALLARDO VÁSQUEZ, ESTEBAN ANDRÉS",
        "GALLO DE TRENQUALYE, JOSÉ MIGUEL",
        "GARCÍA DE LA HUERTA ROJAS, ALICIA",
        "KITA TAMASHIRO, SARA SIZUE",
        "KOLUBAKIN DE LA JARA, AGUSTINA",
        "LEHUEDÉ DÍAZ, TOMÁS",
        "LIBEDINSKY HAN, GABRIEL DOV",
        "MARTÍNEZ MARTÍNEZ, JOAQUÍN ALFONSO",
        "MARTÍNEZ MATUS, FERNANDO ANDRÉS",
        "MATTA CABRERA, JOSÉ",
        "NAVARRO ARAVENA, DANIEL IGNACIO",
        "PATIÑO SOLÍS, BÁRBARA",
        "PÉREZ ZAMORANO, FRANCISCA IGNACIA",
        "PHILIPPI YUNUSIC, NICOLÁS",
        "PUELMA VERGARA, ANTONIA ISIDORA",
        "REYES BECKER, TOMÁS FRANCISCO",
        "REYES COVARRUBIAS, BENJAMÍN ALONSO",
        "RIESCO VALDÉS, MARIA MERCEDES",
        "RIVADENEIRA BEZANILLA, LEÓN",
        "RIVAS VÁSQUEZ, JOAQUÍN RICARDO SEGUNDO",
        "ROJAS ARIAS, FRANCISCO ARTURO",
        "ROZAS VARGAS, JORGE",
        "SALAS GONZÁLEZ, VANESSA ALEJANDRA",
        "SANHUEZA PINO, IGNACIO ALONSO",
        "SAUMA GUZMÁN, TRINIDAD CONSTANZA",
        "SOBARZO VIDAL, DAVID ALEJANDRO",
        "SOTO MUENA, LUIS IGNACIO",
        "SOTO RODRÍGUEZ, VIVIANA FRANCISCA",
        "TASSARA MOLINA, VITTORIO VINCENZO",
        "VERGARA URETA, AGUSTÍN JESÚS",
        "VÍLCHEZ URIBE, VALERY DANIELA",
        "WEIFFENBACH VIVES, SOFÍA",
        "WITTIG ALTMANN, TOMÁS",
        "YÁÑEZ ANDRADE, MARTÍN SAMUEL"
      ],
      "scores": [
        [
          0,
          5,
          5,
          4,
          0,
          4,
          3,
          1
        ],
        [
          4,
          0,
          0,
          0,
          5,
          5,
          3,
          3
        ],
        [
          5,
          0,
          0,
          5,
          0,
          5,
          4,
          0
        ],
        [
          3,
          2,
          2,
          5,
          5,
          4,
          3,
          4
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          3,
          1
        ],
        [
          5,
          5,
          5,
          4,
          4,
          5,
          4,
          4
        ],
        [
          0,
          4,
          4,
          5,
          4,
          4,
          3,
          2
        ],
        [
          0,
          4,
          4,
          0,
          5,
          4,
          0,
          0
        ],
        [
          4,
          4,
          4,
          4,
          5,
          3,
          4,
          5
        ],
        [
          4,
          3,
          3,
          5,
          5,
          3,
          3,
          3
        ],
        [
          0,
          5,
          5,
          3,
          0,
          0,
          4,
          0
        ],
        [
          0,
          0,
          0,
          5,
          5,
          5,
          3,
          1
        ],
        [
          3,
          5,
          5,
          0,
          4,
          5,
          0,
          4
        ],
        [
          3,
          3,
          3,
          0,
          5,
          4,
          3,
          2
        ],
        [
          3,
          5,
          5,
          0,
          5,
          0,
          4,
          0
        ],
        [
          0,
          5,
          5,
          3,
          5,
          4,
          5,
          2
        ],
        [
          3,
          3,
          3,
          3,
          0,
          2,
          3,
          2
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          2,
          2
        ],
        [
          0,
          4,
          4,
          5,
          4,
          4,
          4,
          1
        ],
        [
          4,
          5,
          5,
          4,
          4,
          5,
          4,
          3
        ],
        [
          5,
          5,
          5,
          4,
          5,
          4,
          2,
          3
        ],
        [
          0,
          5,
          5,
          0,
          5,
          0,
          0,
          3
        ],
        [
          0,
          3,
          3,
          5,
          0,
          4,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          4,
          3,
          4,
          1
        ],
        [
          3,
          5,
          5,
          0,
          5,
          5,
          3,
          1
        ],
        [
          2,
          4,
          4,
          5,
          5,
          4,
          4,
          1
        ],
        [
          0,
          5,
          5,
          5,
          5,
          5,
          3,
          2
        ],
        [
          0,
          5,
          5,
          4,
          0,
          0,
          0,
          0
        ],
        [
          0,
          5,
          5,
          4,
          4,
          4,
          4,
          1
        ],
        [
          0,
          5,
          5,
          5,
          4,
          5,
          4,
          0
        ],
        [
          5,
          5,
          5,
          5,
          5,
          5,
          3,
          0
        ],
        [
          0,
          5,
          5,
          5,
          5,
          5,
          2,
          1
        ],
        [
          4,
          3,
          3,
          4,
          3,
          0,
          3,
          3
        ],
        [
          0,
          4,
          4,
          5,
          5,
          5,
          4,
          1
        ],
        [
          0,
          5,
          5,
          3,
          5,
          4,
          0,
          1
        ],
        [
          0,
          0,
          0,
          4,
          4,
          0,
          3,
          1
        ],
        [
          5,
          5,
          5,
          4,
          4,
          4,
          3,
          5
        ],
        [
          0,
          5,
          5,
          0,
          2,
          5,
          0,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          4,
          0,
          0
        ],
        [
          0,
          0,
          0,
          5,
          4,
          5,
          3,
          3
        ],
        [
          0,
          3,
          3,
          0,
          4,
          4,
          3,
          1
        ],
        [
          0,
          5,
          5,
          0,
          0,
          5,
          4,
          1
        ],
        [
          4,
          2,
          2,
          5,
          5,
          5,
          3,
          3
        ],
        [
          0,
          5,
          5,
          0,
          5,
          5,
          0,
          4
        ],
        [
          4,
          5,
          5,
          5,
          5,
          5,
          3,
          3
        ],
        [
          4,
          5,
          5,
          4,
          4,
          3,
          3,
          1
        ],
        [
          4,
          5,
          5,
          5,
          5,
          5,
          3,
          2
        ],
        [
          0,
          0,
          0,
          4,
          5,
          3,
          2,
          2
        ],
        [
          3,
          2,
          2,
          4,
          5,
          4,
          4,
          2
        ],
        [
          4,
          5,
          5,
          5,
          5,
          4,
          4,
          3
        ],
        [
          5,
          5,
          5,
          4,
          4,
          5,
          4,
          2
        ],
        [
          5,
          5,
          5,
          5,
          4,
          5,
          4,
          4
        ],
        [
          5,
          5,
          5,
          5,
          5,
          5,
          3,
          1
        ],
        [
          4,
          5,
          5,
          3,
          5,
          5,
          3,
          2
        ],
        [
          2,
          5,
          5,
          5,
          5,
          5,
          0,
          2
        ],
        [
          4,
          3,
          0,
          4,
          3,
          2,
          0,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          4,
          2,
          2,
          1
        ],
        [
          5,
          5,
          5,
          4,
          5,
          3,
          4,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          0
        ],
        [
          4,
          5,
          5,
          5,
          5,
          3,
          3,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3
        ],
        [
          4,
          4,
          5,
          4,
          5,
          5,
          0,
          3
        ],
        [
          5,
          4,
          5,
          4,
          4,
          4,
          4,
          2
        ],
        [
          5,
          5,
          5,
          5,
          4,
          5,
          3,
          3
        ],
        [
          0,
          5,
          4,
          4,
          0,
          2,
          4,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          2,
          0,
          1
        ],
        [
          0,
          3,
          5,
          0,
          5,
          5,
          0,
          3
        ],
        [
          4,
          2,
          5,
          4,
          5,
          3,
          3,
          1
        ],
        [
          5,
          5,
          5,
          5,
          4,
          3,
          3,
          0
        ],
        [
          5,
          0,
          0,
          4,
          0,
          0,
          0,
          3
        ],
        [
          3,
          5,
          4,
          5,
          5,
          4,
          0,
          2
        ],
        [
          4,
          4,
          5,
          3,
          4,
          2,
          3,
          1
        ],
        [
          0,
          5,
          5,
          5,
          4,
          4,
          3,
          4
        ],
        [
          0,
          3,
          5,
          0,
          5,
          5,
          3,
          1
        ],
        [
          0,
          4,
          5,
          0,
          4,
          0,
          3,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          5,
          4,
          2,
          2
        ],
        [
          5,
          4,
          5,
          4,
          5,
          5,
          4,
          2
        ],
        [
          5,
          5,
          5,
          4,
          4,
          4,
          4,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          0,
          4,
          3,
          0,
          0
        ],
        [
          5,
          3,
          4,
          4,
          5,
          1,
          2,
          1
        ],
        [
          4,
          5,
          4,
          5,
          5,
          4,
          5,
          2
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        [
          5,
          5,
          5,
          4,
          5,
          3,
          2,
          3
        ],
        [
          0,
          3,
          5,
          4,
          4,
          3,
          4,
          1
        ],
        [
          4,
          5,
          5,
          4,
          5,
          4,
          4,
          3
        ],
        [
          4,
          5,
          5,
          4,
          4,
          3,
          2,
          3
        ],
        [
          4,
          5,
          0,
          4,
          4,
          4,
          4,
          1
        ],
        [
          0,
          1,
          5,
          3,
          3,
          0,
          0,
          1
        ],
        [
          3,
          5,
          0,
          0,
          3,
          0,
          0,
          0
        ],
        [
          3,
          4,
          5,
          4,
          5,
          2,
          3,
          1
        ],
        [
          3,
          5,
          5,
          0,
          5,
          4,
          5,
          3
        ],
        [
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0
        ],
        [
          3,
          4,
          5,
          5,
          5,
          2,
          3,
          1
        ],
        [
          5,
          5,
          5,
          5,
          5,
          3,
          0,
          1
        ],
        [
          4,
          5,
          5,
          5,
          5,
          4,
          0,
          1
        ],
        [
          3,
          5,
          4,
          5,
          5,
          4,
          3,
          0
        ],
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          2
        ],
        [
          5,
          5,
          5,
          4,
          5,
          2,
          0,
          2
        ],
        [
          5,
          5,
          5,
          4,
          4,
          3,
          5,
          3
        ]
      ],
      "totals": [
        22,
        20,
        19,
        28,
        27,
        36,
        26,
        17,
        33,
        29,
        17,
        19,
        26,
        23,
        22,
        29,
        19,
        27,
        26,
        34,
        33,
        18,
        15,
        12,
        27,
        29,
        30,
        14,
        27,
        28,
        33,
        28,
        23,
        28,
        23,
        12,
        35,
        19,
        0,
        4,
        20,
        18,
        20,
        29,
        24,
        35,
        29,
        34,
        16,
        26,
        35,
        34,
        37,
        34,
        32,
        29,
        18,
        0,
        28,
        33,
        5,
        33,
        3,
        30,
        32,
        35,
        21,
        3,
        21,
        27,
        30,
        12,
        28,
        26,
        30,
        22,
        18,
        0,
        32,
        34,
        34,
        0,
        22,
        25,
        34,
        0,
        0,
        32,
        24,
        34,
        30,
        26,
        13,
        11,
        27,
        30,
        3,
        28,
        29,
        29,
        29,
        2,
        28,
        34
      ]
    },
    "ranking": {
      "names": [
        "WAHL GONZÁLEZ, MARÍA SOFÍA",
        "BUSTOS DE LA FUENTE, IGNACIO",
        "PADILLA VERA, MATÍAS AGUSTÍN",
        "VALENZUELA MIRANDA, MARTÍN",
        "VIEL DE LA MAZA, RAIMUNDO",
        "CERDA OYARZÚN, JUAN PABLO",
        "HERRERA DEL REAL, BARTOLOMÉ JOSÉ",
        "VASCONCELLO ORTIZ, ANGELO NICOLÁS",
        "VILLARROEL MELLADO, CONSTANZA ANDREA",
        "YACONI IRÍZAR, LUCAS",
        "MATTA CABRERA, JOSÉ",
        "NAVARRO ARAVENA, DANIEL IGNACIO",
        "PUELMA VERGARA, ANTONIA ISIDORA",
        "RIVAS VÁSQUEZ, JOAQUÍN RICARDO SEGUNDO",
        "YÁÑEZ ANDRADE, MARTÍN SAMUEL"
      ],
      "totals": [
        37,
        36,
        35,
        35,
        35,
        35,
        34,
        34,
        34,
        34,
        34,
        34,
        34,
        34,
        34
      ]
    }
  },
  "sectionNames": [
    "Sección 1",
    "Sección 2",
    "Ambas Secciones"
  ],
  "maxPerControl": 5,
  "generatedAt": "2026-03-25"
};
